version: '3.7'

networks:
  ssh_network:

services:
  mysql:
    image: mysql:5.7.16
    container_name: ssh-mysql
    hostname: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: password
    mem_limit: 512m
    ports:
      - '32780:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ssh_network
  ssh-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh-server
    ports:
      - "20022:22"
    networks:
      - ssh_network
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
